services:
  api:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - ${DOCKER_DB_FOLDER}:/app/db/
    environment:
        - PORT=8080
        - DB_FILE=/app/db/gocms.db
    env_file:
      - ./.env
