services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile.backend
    image: gohcms-backend
    env_file:
      - .env
    ports:
      - "${APP_API_PORT}:${APP_API_PORT}"
    networks:
      - back-net
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.frontend
    image: gohcms-frontend
    env_file:
      - .env
    ports:
      - "${APP_FRONT_PORT}:80"
    networks:
      - front-net
  db:
    image: mongo:6.0.2
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gohcms
    volumes:
      - ./mongodbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - back-net

networks:
  front-net:
  back-net:
