services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    networks:
      - back-net
  frontend:
    build: web/admin-gui/.
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:80"
    networks:
      - front-net
  db:
    image: mongo:6.0.2
    # ports:
    #   - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gohcms
    volumes:
      - ./mongodbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - back-net

networks:
  front-net:
  back-net:
