FROM node:latest as build-stage
WORKDIR /app
COPY ./web/admin-gui/package*.json ./
COPY ./.env ./
RUN npm install
COPY ./web/admin-gui/ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./web/admin-gui/nginx.conf /etc/nginx/nginx.conf
