# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "development"
      HOST: "http://localhost:42069"
      PORT: "42069"
      JWT_SECRET: gpehf28ugohfevuwpf98hv9ewvb
      CORS_ALLOWED_ORIGINS: "*"
      DB_FILE: "./gohcms.db"
      SMTP_EMAIL: floriansylvain@mailo.com
      SMTP_PASSWORD: bqICDqGtfV1R
      SMTP_HOST: mail.mailo.com
      SMTP_PORT: 587
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
